/** High-signal keywords — shared across news-impact sources */
export const IMPACT_KEYWORDS = [
  "hack",
  "hacked",
  "exploit",
  "exploited",
  "drained",
  "rug",
  "scam",
  "listing",
  "lists",
  "delist",
  "delisting",
  "regulation",
  "regulatory",
  "sec ",
  "cftc",
  "lawsuit",
  "charges",
  "etf",
  "approval",
  "approved",
  "partnership",
  "partners with",
  "whale",
  "liquidation",
  "liquidated",
  "bankruptcy",
  "insolvent",
  "halt",
  "suspended",
  "ban",
  "banned",
  "outflow",
  "inflow",
  "breakout",
  "crash",
  "surge",
  "rally",
  "binance",
  "coinbase",
  "blackrock",
  "federal reserve",
  "rate cut",
  "rate hike",
  "depeg",
  "mainnet",
  "unlock",
  "sanction",
  "oracle",
  "bridge",
  "transferred",
  "deposit",
  "withdraw",
] as const;
