"""Execution pattern registry — hypotheses about large-order behavior."""

from __future__ import annotations

from typing import Any

PATTERNS: dict[str, dict[str, Any]] = {
    "level_defense": {
        "id": "level_defense",
        "category": "liquidity_dynamics",
        "question": "Что происходит после статистически экстремальной защиты уровня?",
        "description": "Быстрое восстановление глубины + пассивное доминирование у ключевого уровня.",
        "feature": "liquidity_refill_pct",
        "quantile": "q99",
        "economic": "Крупный участник защищает уровень лимитными заявками — краткосрочная стабилизация или подготовка к продолжению исполнения.",
    },
    "liquidity_pull": {
        "id": "liquidity_pull",
        "category": "liquidity_dynamics",
        "question": "Что происходит после снятия ликвидности?",
        "description": "Резкое статистическое падение глубины стакана.",
        "feature": "liquidity_vanish_pct",
        "quantile": "q99",
        "economic": "Маркет-мейкеры или крупный участник снимает котировки — риск импульса или ложной ликвидности.",
    },
    "fake_liquidity": {
        "id": "fake_liquidity",
        "category": "hidden_liquidity",
        "question": "Ложная ликвидность — depth vanish без агрессивного потока?",
        "description": "Глубина исчезает при низком trade footprint (статистический хвост vanish / footprint).",
        "feature": "liquidity_vanish_pct",
        "quantile": "q95",
        "flag": "footprint_z < footprint_z.quantile(0.25)",
        "economic": "Отображаемая ликвидность не подкреплена реальным исполнением — spoofing или отмена перед ударом.",
    },
    "aggressive_absorption": {
        "id": "aggressive_absorption",
        "category": "aggressive_execution",
        "question": "Поглощение агрессивных ордеров без движения цены?",
        "description": "Экстремальный absorption_ratio при высоком агрессивном потоке.",
        "feature": "absorption_ratio",
        "quantile": "q99",
        "economic": "Пассивный крупный участник поглощает поток — возможен разворот или продолжение TWAP/VWAP.",
    },
    "spread_hold": {
        "id": "spread_hold",
        "category": "mm_behavior",
        "question": "Удержание спреда после импульса?",
        "description": "MM сужает/удерживает spread при движении mid (spread_hold_score в верхнем квантиле).",
        "feature": "spread_hold_score",
        "quantile": "q99",
        "economic": "Маркет-мейкер контролирует спред — снижение краткосрочной волатильности или накопление.",
    },
    "spread_widen": {
        "id": "spread_widen",
        "category": "mm_behavior",
        "question": "Расширение спреда после импульса?",
        "description": "Экстремальный рост spread_bps или spread_chg_bps.",
        "feature": "spread_chg_bps",
        "quantile": "q99",
        "economic": "MM расширяет спред из-за риска — задержка реакции, возможен follow-through.",
    },
    "post_impulse_shift": {
        "id": "post_impulse_shift",
        "category": "large_footprint",
        "question": "Смена поведения после импульса?",
        "description": "Экстремальное взаимодействие mid_ret × spread_chg.",
        "feature": "post_impulse_shift",
        "quantile": "q99",
        "economic": "Режим исполнения меняется после импульса — переход passive ↔ aggressive.",
    },
    "support_vanish": {
        "id": "support_vanish",
        "category": "liquidity_dynamics",
        "question": "Исчезновение поддержки bid-side?",
        "description": "Экстремальное падение bid_depth при отрицательном imbalance.",
        "feature": "bid_depth",
        "quantile": "q01",
        "economic": "Поддержка снята — риск каскада или завершения крупной покупки.",
    },
    "new_defense": {
        "id": "new_defense",
        "category": "liquidity_dynamics",
        "question": "Появление новой защиты?",
        "description": "Резкий рост depth + положительный imbalance (replenishment).",
        "feature": "liquidity_refill_pct",
        "quantile": "q95",
        "economic": "Новый защитный уровень — крупный лимитный участник.",
    },
    "execution_completion": {
        "id": "execution_completion",
        "category": "large_footprint",
        "question": "Признаки завершения крупного ордера?",
        "description": "Падение footprint + снижение trade_count после экстремального footprint_z.",
        "feature": "footprint_z",
        "quantile": "q90",
        "flag": "trade_count < trade_count.quantile(0.20)",
        "economic": "Крупное исполнение завершено — снятие давления, mean-reversion или новый этап.",
    },
    "twap_signature": {
        "id": "twap_signature",
        "category": "twap",
        "question": "Статистические признаки TWAP-исполнения?",
        "description": "Высокая равномерность объёма по временным корзинам.",
        "feature": "twap_uniformity",
        "quantile": "q99",
        "economic": "Алгоритмическое равномерное исполнение — предсказуемый краткосрочный дрейф.",
    },
    "vwap_signature": {
        "id": "vwap_signature",
        "category": "vwap",
        "question": "Статистические признаки VWAP-исполнения?",
        "description": "Цена удерживается около VWAP (низкое |vwap_dev| в нижнем квантиле при высоком объёме).",
        "feature": "vwap_dev_bps",
        "quantile": "q05",
        "flag": "large_trade_ratio > large_trade_ratio.quantile(0.75)",
        "economic": "Исполнение привязано к VWAP — mean-reversion к якорю объёма.",
    },
    "iceberg_refill": {
        "id": "iceberg_refill",
        "category": "iceberg",
        "question": "Iceberg — пополнение скрытой ликвидности?",
        "description": "Высокий iceberg_score (refill × large trades).",
        "feature": "iceberg_score",
        "quantile": "q99",
        "economic": "Скрытый крупный лимитный ордер пополняется после исполнения видимой части.",
    },
    "passive_execution": {
        "id": "passive_execution",
        "category": "passive_execution",
        "question": "Доминирование пассивного исполнения?",
        "description": "Экстремальный passive_dominance при низком mid_ret.",
        "feature": "passive_dominance",
        "quantile": "q99",
        "economic": "Крупный участник набирает позицию лимитами — низкая немедленная ценовая реакция.",
    },
    "aggressive_execution": {
        "id": "aggressive_execution",
        "category": "aggressive_execution",
        "question": "Агрессивное исполнение крупного ордера?",
        "description": "Экстремальный aggressive_dominance + large_trade_ratio.",
        "feature": "aggressive_dominance",
        "quantile": "q99",
        "economic": "Срочное исполнение через рынок — импульс, проскальзывание, информационный сигнал.",
    },
    "liquidity_refill": {
        "id": "liquidity_refill",
        "category": "liquidity_refill",
        "question": "Быстрое восстановление ликвидности?",
        "description": "Статистически экстремальный liquidity_refill_pct.",
        "feature": "liquidity_refill_pct",
        "quantile": "q99",
        "economic": "MM или алгоритм восстанавливает стакан — стабилизация перед следующей фазой.",
    },
    "queue_dynamics": {
        "id": "queue_dynamics",
        "category": "queue_dynamics",
        "question": "Экстремальное давление в очереди?",
        "description": "queue_pressure = imbalance × flow в верхнем квантиле.",
        "feature": "queue_pressure",
        "quantile": "q99",
        "economic": "Перекос очереди лимитных заявок — приоритет исполнения смещается.",
    },
    "large_footprint": {
        "id": "large_footprint",
        "category": "large_footprint",
        "question": "След крупного участника?",
        "description": "Экстремальный footprint_z (объём относительно глубины).",
        "feature": "footprint_z",
        "quantile": "q99",
        "economic": "Концентрированная активность крупного участника — информационный след.",
    },
    "inventory_unwind": {
        "id": "inventory_unwind",
        "category": "inventory_unwind",
        "question": "Разгрузка инвентаря MM/крупного участника?",
        "description": "Экстремальный inventory_unwind_score.",
        "feature": "inventory_unwind_score",
        "quantile": "q99",
        "economic": "Сброс накопленной позиции — краткосрочное давление на цену.",
    },
    "mm_spread_management": {
        "id": "mm_spread_management",
        "category": "mm_behavior",
        "question": "Изменение поведения MM по спреду и глубине?",
        "description": "Экстремальный mm_spread_mgmt = spread × depth_chg.",
        "feature": "mm_spread_mgmt",
        "quantile": "q99",
        "economic": "MM одновременно меняет спред и глубину — смена режима котирования.",
    },
}


def list_patterns() -> list[str]:
    return list(PATTERNS.keys())


def get_pattern(pattern_id: str) -> dict[str, Any]:
    if pattern_id not in PATTERNS:
        raise KeyError(f"Unknown pattern: {pattern_id}")
    return PATTERNS[pattern_id]
